### ISSUE TITLE
Anyfile does not start

### ISSUE THREAD

**Issue by softmkr** [julsemaan/anyfile-notepad#12]
Hi there!

I'm having trouble opening files with Anyfile text editor, it does not open the file.

The issue started several days ago.

When I try to open any file from my google drive it appears the message "Starting up application - Hang tight..." and that's all.

It does not load the file.

I'll appreciate any help.

Regards,
Rubén

**Comment by julsemaan** [comment]
Could you right click on the page, then click inspect. It will open a console at the bottom or at the right, select the "Console" tab and take a screenshot which you can paste here.

That should give me what I need to figure it out. 

Thanks!

**Comment by softmkr** [comment]
Hi
The console tab show this message:
"The resource https://pagead2.googlesyndication.com/pagead/js/r20190522/r20190131/show_ads_impl.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally."

Regards, 
Rubén Trejo Colmenero
 

    El martes, 28 de mayo de 2019 19:39:20 GMT-5, Julien Semaan <notifications@github.com> escribió:  
 
 
Could you right click on the page, then click inspect. It will open a console at the bottom or at the right, select the "Console" tab and take a screenshot which you can paste here.

That should give me what I need to figure it out.

Thanks!

**Comment by julsemaan** [comment]
Can you try to clear your browser cache and disable your ad-blocker temporarily if you have one
