### ISSUE TITLE
Check spelling doesn't works with anyfile-notepad

### ISSUE THREAD

**Issue by sara-rodriguez** [julsemaan/anyfile-notepad#14]
In Chrome and Firefox the check spelling doesn't works in anyfile-notepad, if this is intentional, please let the user select if he wants or not this feature.

Regards

**Comment by julsemaan** [comment]
I can try to see if this can be enabled on demand.

I'm not doing anything explicit to disable it but it could be because of the fact the editor is not a textarea and uses complex rendering

**Comment by julsemaan** [comment]
It seems like spelling check isn't compatible with ace.js which uses complex rendering (its not a simple textarea)

Firefox seems to support enabling as per https://github.com/ajaxorg/ace/issues/2107

I'll see if I can add spell checking as a feature for all browsers, until then I'll add the workaround describe in the issue above shortly but that will only work for Firefox
