### ISSUE TITLE
Cancel billing

### ISSUE THREAD

**Issue by GaryFurash** [julsemaan/anyfile-notepad#15]
I am getting billed 3.99 from anyfile notepad. Please cancel.

**Comment by julsemaan** [comment]
First, this isn't the place to request this.

Second, you already got this cancelled through your credit card company which had me pay a nice 15$ service fee.

**Comment by julsemaan** [comment]
Got you confused with another user, you can cancel the subscription in the app via the help menu. If you can't access that let me know

**Comment by GaryFurash** [comment]
Sorry. I'm happy to keep paying for it. I thought you stopped supporting it -maybe I was confused. This is a very good app and worth the $4/year fee.
