### ISSUE TITLE
Preferences could not be loaded

### ISSUE THREAD

**Issue by AutomationMan808** [julsemaan/anyfile-notepad#16]
This may be a change in Google Drive API but wanted to let you know.

**Comment by julsemaan** [comment]
It seems that Google has recently pushed a change to their API to download files which is missing a core component the browser required (CORS headers).

I was able to replicate your issue but unfortunately I can't do anything until Google addresses the issue.

I was able to find other folks hosting apps who are getting similar issues that were reported today.

Let's hope that Google will be reactive on this.

Cheers!

**Comment by julsemaan** [comment]
This should be fixed now. Currently still in talks with the Google team to see if this will reappear.
