### ISSUE TITLE
Unstable

### ISSUE THREAD

**Issue by rajubjc** [julsemaan/anyfile-notepad#17]
I know that it is free. My humble request to make it stable. The problem is after using it for some time, it is hanging my system. The pointer flickers and my browser and my system hangs. Kindly look into it.

**Comment by julsemaan** [comment]
I will take a look into it and report my findings here

**Comment by julsemaan** [comment]
Hi,

I tried to replicate the issue without success.

I left the app running for a long time with a file that I did some changes and watched the RAM usage.

It stayed consistent across my test.

Can you provide more details around how to replicate this.

Thanks,

**Comment by rajubjc** [comment]
I am using anyfile-notepad in association with colab and Google drive. Like
the contents of the notepad is usually a python file. So, I have to make
frequent changes and save it. Sometimes after making a change I ll try to
mount my drive in colab. And I run the file. After doing this a few times,
it behaved as I described.

Thanks

**Comment by julsemaan** [comment]
And it does it after how much time of usage? 15 minutes, an hour, multiple hours?

**Comment by rajubjc** [comment]
Usually an hour or two. Not greater than that.

**Comment by julsemaan** [comment]
Closing this, was never able to accurately replicate the issue. Please reopen if you have a way to replicate the issue or are able to extract debug and performance information from your browser
