### ISSUE TITLE
There are still a few references to the G+ community in the FAQ

### ISSUE THREAD

**Issue by NoSubstitute** [julsemaan/anyfile-notepad#21]
https://anyfile-notepad.semaan.ca/faq

**Comment by julsemaan** [comment]
Thanks for submitting this, these pages do need a cleanup and the Facebook community that replaces it is hard to maintain and full of spam to manage.

I'll need to switch to a contact form and adjust all the references to G+ and the soon to be outdated Facebook community

**Comment by NoSubstitute** [comment]
You could just stick with github.

**Comment by julsemaan** [comment]
Added a contact form (since a lot of users don't use GH) and did a cleanup of the FB and G+ references. Thanks for posting this, let me know if I forgot any of them
